### ISSUE TITLE
How  to do CBC-PKCS7 and iv=MD5(key)?

### ISSUE THREAD

**Issue by s349856186** [AKushWarrior/steel_crypt#23] opened 2020-02-28 00:55 UTC
I used JS encrypt as below:
CryptoJS.AES.encrypt(pw, SHA256(key), {iv:MD5(key), mode:CBC, padding:Pkcs7})

How to do use this crypt ? Thanks

**Comment by AKushWarrior** [comment] 2020-03-01 19:52
Okay, so this is how you do this here:

```dart
import 'package:steel_crypt/steel_crypt.dart';
var hash1 = HashCrypt('SHA-256');
var hash2 = HashCrypt('MD5');
var keyAES = hash1.hash(key); //If key is the same variable from your example
print(AesCrypt(keyAES, 'cbc', 'pkcs7').encrypt(pw); //if pw is the same variable from your example
```

Lemme know if you have questions or issues. Closing this for now.

**Comment by s349856186** [comment] 2020-03-03 07:08
@AKushWarrior
Thanks for your reply.
var pw = "1234";
    var key = "123";
    var hash1 = HashCrypt('SHA-256');
    var hash2 = HashCrypt('MD5');
    var keyAES = hash1.hash(key);
    var pwd = AesCrypt(keyAES, 'cbc', 'pkcs7').encrypt(pw);
    print("=log=111="+pwd);
But hash2 not used, and the code get error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Initialization vector must be the same length as block size

**Comment by AKushWarrior** [comment] 2020-03-03 14:12
@s349856186 whoops. The below should work.

```dart
import 'package:steel_crypt/steel_crypt.dart';
var hash1 = HashCrypt('SHA-256');
var hash2 = HashCrypt('MD5');
var keyAES = hash1.hash(key); //If key is the same variable from your example
print(AesCrypt(keyAES, 'cbc', 'pkcs7').encrypt(pw, hash2.hash(key))); //if pw and key are the same variables from your example
```

**Comment by s349856186** [comment] 2020-03-06 04:45
@AKushWarrior
Thanks for your reply.
I tried this method before and still got the same error, so I do n’t know how to use it.
Can you help me，Thanks

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Initialization vector must be the same length as block size

**Comment by s349856186** [comment] 2020-03-19 07:06
@AKushWarrior
Can you help me，Thanks

**Comment by AKushWarrior** [comment] 2020-03-19 18:38
Sorry, I wasn't monitoring this issue for some reason. I'll take a look...

**Comment by AKushWarrior** [comment] 2020-03-20 03:34
Ah. The problem is that AES uses UTF-16 codeunits, whereas HashCrypt() uses base64 encoding/decoding. 

This will be fixed in steel_crypt 2.0. Tune into #22 .

**Comment by AKushWarrior** [comment] 2020-05-22 19:03
Okay, what I said was not the problem at all. You should use the new "raw" classes, and just take the first 16 digits of the hash as the iv.

**Closed as completed by AKushWarrior** 2020-05-22 19:03 UTC
Labels: educational, clarification

**Comment by AKushWarrior** [comment] 2020-05-22 19:11
I can't give you a concrete code example until you give me what encoding CryptoJS uses.
